# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 513)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tw = QtWidgets.QTableWidget(self.centralwidget)
        self.tw.setGeometry(QtCore.QRect(20, 70, 761, 391))
        self.tw.setObjectName("tw")
        self.tw.setColumnCount(7)
        self.tw.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw.setHorizontalHeaderItem(6, item)
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(30, 20, 131, 31))
        self.btn1.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(200, 20, 131, 31))
        self.btn2.setStyleSheet("background-color: rgb(206, 206, 206);")
        self.btn2.setObjectName("btn2")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(380, 20, 371, 31))
        self.label1.setText("")
        self.label1.setObjectName("label1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Капучино"))
        item = self.tw.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tw.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Название сорта"))
        item = self.tw.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Степень обжарки"))
        item = self.tw.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Молотый / в зернах"))
        item = self.tw.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Описание вкуса"))
        item = self.tw.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Цена (руб.)"))
        item = self.tw.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Объем упаковки (г)"))
        self.btn1.setText(_translate("MainWindow", "Добавить"))
        self.btn2.setText(_translate("MainWindow", "Изменить"))
